services:
  container_bass:
    build: .
    hostname: dubiandubaian
    volumes:
      - dubian_data:/home/dubian
    ports:
      - "443:443"
    privileged: true
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color

volumes:
  dubian_data:
